name: Create demo issue 3

on:
  push:
jobs:

  msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simple demo for reusable workflow"
    
  info:
    uses: rndrepos/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "Test issue 3"
      body: "Test body 3"
