name: create-repo-issue4
  
on: 
  push
        
jobs:
 
  create_issue:
    runs-on: ubuntu-latest 
  
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          response=$(curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.PAT }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "simple title",
            "body": "simple body"
            }' \
          --fail)
          echo "response from curl=$response"
