name: Create Issue

on:
  push:
  
jobs:
  info:
    uses: rndrepos/common/.github/workflows/create-repo-issue.yml@main
    token: ${{ secrets.PAT }} 
    with:
      title: "Test issue"
      body: "Test body"
