name: Create demo issue 5
on:
  push:
  
jobs: 
  get-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  create-new-issue:
    uses: rndrepos/common/.github/workflows/create-issue-via-gh.yml@main
    needs: get-repo
    secrets: inherit
    with:
      title: "Test issue"
      body: "Test body"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-number }}
