name: Create demo issue 3

on:
  push:
  
jobs:

  msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simple demo for reusable workflow"
    
  create-new-issue:
    uses: rndrepos/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "Test issue 3"
      body: "Test body 3"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo New issue number = ${{ needs.create-new-issue.outputs.number }}
